# TODO: Utiliser l'image python:3.10-slim comme image de base
FROM 

# TODO: Définir le répertoire de travail
WORKDIR 

# TODO: Copier le fichier requirements.txt
COPY 

# TODO: Installer les dépendances
RUN 

# TODO: Copier le reste des fichiers de l'application
COPY 

# TODO: Exposer le port 5000
EXPOSE 

# TODO: Lancer l'application Flask
CMD 

